-- -- MySQL Script generated by MySQL Workbench
-- -- Fri Dec  6 23:44:43 2019
-- -- Model: New Model    Version: 1.0
-- -- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -- -----------------------------------------------------
-- -- Schema Record_library
-- -- -----------------------------------------------------

-- -- -----------------------------------------------------
-- -- Schema Record_library
-- -- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `Record_library` DEFAULT CHARACTER SET utf8;
-- USE `Record_library` ;

-- -----------------------------------------------------
-- Table  `Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Countries` (
  `Cod_country`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Name_country` TEXT NOT NULL
  );



-- -----------------------------------------------------
-- Table  `Disk_format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Disk_format` (
  `Cod_formata`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Vid_formata` TEXT NOT NULL
);



-- -----------------------------------------------------
-- Table  `Vid_diska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Vid_diska` (
  `Cod_vida_diska`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Name_vida` TEXT NOT NULL
);



-- -----------------------------------------------------
-- Table  `Singers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Singers` (
  `Cod_singer`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  `Name_singer` TEXT NOT NULL
);



-- -----------------------------------------------------
-- Table  `Producers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Producers` (
  `Cod_producer`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Name_producer` TEXT NOT NULL,
  `Note` TEXT NULL
  );



CREATE TABLE IF NOT EXISTS  `Comments` (
  `id_comment`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `value` TEXT NOT NULL,
  `Cod_diska` INTEGER NOT NULL
  );


-- -----------------------------------------------------
-- Table  `Music_Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Music_Films` (
  `Cod_diska`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Name_diska` TEXT NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `Cod_vida_diska`    INTEGER NOT NULL,
  `Cod_formata`    INTEGER NOT NULL,
  `Cod_producer`    INTEGER NULL,
  `Cod_singer`    INTEGER NULL,
  `Cod_country`    INTEGER NOT NULL
);



-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -- -----------------------------------------------------
-- -- Data for table  `Countries`
-- -- -----------------------------------------------------

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- START TRANSACTION;




-- START TRANSACTION;
-- USE `Record_library`;
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Россия');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'США');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Германия');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Великобритания');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Италия');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Турция');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Польша');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Франция');
INSERT INTO  `Countries` ( `Name_country`) VALUES ( 'Украина');

-- COMMIT;


-- -- -----------------------------------------------------
-- -- Data for table  `Disk_format`
-- -- -----------------------------------------------------
-- START TRANSACTION;
-- USE `Record_library`;
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'dvd');
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'dvdrw');
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'cd');
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'cdrw');
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'dvdr');
INSERT INTO  `Disk_format` ( `Vid_formata`) VALUES ( 'cdr');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table  `Vid_diska`
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE `Record_library`;
INSERT INTO  `Vid_diska` ( `Name_vida`) VALUES ( 'Music');
INSERT INTO  `Vid_diska` ( `Name_vida`) VALUES ( 'Films');

-- COMMIT;


-- -- -----------------------------------------------------
-- -- Data for table  `Singers`
-- -- -----------------------------------------------------
-- START TRANSACTION;
-- USE `Record_library`;
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Saint Jhn');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Pascal Letoublon');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Maruv');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Lodoba');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Алексей Сулима');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Ленинград');
INSERT INTO  `Singers` (`Name_singer`) VALUES ( 'Ева Польна');

-- COMMIT;


-- -- -----------------------------------------------------
-- -- Data for table  `Producers`
-- -- -----------------------------------------------------
-- START TRANSACTION;
-- USE `Record_library`;
INSERT INTO  `Producers` (`Name_producer`, `Note`) VALUES ( 'Николас Песке', NULL);
INSERT INTO  `Producers` (`Name_producer`, `Note`) VALUES ( 'Алексей Сидоров', NULL);
INSERT INTO  `Producers` (`Name_producer`, `Note`) VALUES ( 'М. Найт Шьямалан', NULL);

-- COMMIT;


-- -- -----------------------------------------------------
-- -- Data for table  `Music_Films`
-- -- -----------------------------------------------------
-- START TRANSACTION;
-- USE `Record_library`;
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (01, 'Some Nights', '2017', '560', 01, 04, NULL, 01, 04);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (02, 'Siren Song', '2019', '520', 01, 04, NULL, 03, 09);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (03, 'Рыба', '2003', '350', 01, 04, NULL, 06, 01);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (04, 'Пирсинг', '2019', '610', 02, 02, 01, NULL, 02);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (05, 'Небыль', '2019', '490', 01, 06, NULL, 07, 01);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (06, 'Deep House Chill', '2019', '600', 01, 04, NULL, 02, 02);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (07, 'Т-34', '2019', '620', 02, 02, 02, NULL, 01);
-- INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`,   `Cod_producer`, `Cod_singer`, `Cod_country`) VALUES (08, 'Сплит', '2018', '590', 02, 01, 03, NULL, 02);

-- COMMIT;

