-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 23:44:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -- -----------------------------------------------------
-- -- Schema Record_library
-- -- -----------------------------------------------------

-- -- -----------------------------------------------------
-- -- Schema Record_library
-- -- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `Record_library` DEFAULT CHARACTER SET utf8;
-- USE `Record_library` ;

-- -- -----------------------------------------------------
-- -- Table    `Countries`
-- -- -----------------------------------------------------

-- CREATE TABLE IF NOT EXISTS `Comments` (
--   `Id_comment` INT NOT NULL PRIMARY KEY AUTOINCREMENT,
--   `Value` TEXT(100) NOT NULL,
--   `Cod_diska` INT NOT NULL
-- );
-- ENGINE = InnoDB;
-- -- -----------------------------------------------------
-- -- Data for table    `Countries`
-- -- -----------------------------------------------------

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- START TRANSACTION;
--     USE `Record_library`;
    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`) 
    VALUES ( 'Some Nights', '192', '960', 01, 04, 1, 01, 02);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Siren Song', '2014', '1520', 01, 04, 1, 02, 09);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Любовь в Метро ', '2015', '220', 02, 06, 2, 04, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Фарш', '2014', '460', 01, 01, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Вечерний Ленинград', '2012', '890', 02, 02, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Рыба', '2012', '110', 02, 03, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Вечный огонь', '2011', '20', 01, 04, 1, 07, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Аврора', '2007', '1310', 01, 05, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Бабье лето', '2006', '540', 02, 06, 1, 06, 01);
        INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Розовые клоны', '205', '510', 02, 06, 1, 06, 01);

        INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Шут в осаде', '2016', '562', 02, 06, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Как ты там?', '2015', '660', 02, 06, 1, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Как ты там?', '2015', '660', 02, 06, 1, 06, 01);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Привет', '2015', '660', 02, 06, 1, 06, 01);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Ты слишком жизнена', '2015', '220', 02, 06, 1, 06, 01);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Лучший день', '2015', '660', 02, 06, 2, 06, 01);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Я и Девочка', '2015', '660', 02, 06, 2, 06, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Friendships', '2017', '520', 01, 01, 2, 02, 02);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Fall For You', '2018', '260', 02, 02, 2, 02, 02);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Believe In Me', '2018', '4240', 01, 03, 2, 02, 03);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Fall for You - Single', '2006', '540', 01, 04, 2, 02, 02);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Coming Back Around - Single', '2018', '340', 01, 05, 2, 02, 04);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Summer', '2018', '340', 01, 05, 2, 02, 04);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Winter - coming', '2018', '340', 01, 05, 2, 02, 04);




    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Мира мало', '2017', '520', 01, 01, 2, 04, 07);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'INSTADRAMA', '2014', '520', 01, 02, 3, 04, 07);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Парень', '2015', '520', 01, 04, 3, 04, 04);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'случайная', '2018', '520', 02, 06, 3, 04, 04);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Как ты там', '2018', '520', 02, 06, 3, 04, 04);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Веселая', '2018', '520', 02, 06, 3, 04, 04);



    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'To Be Mine', '2019', '520', 01, 01, 1, 03, 06);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Focus On Me', '2018', '320', 01, 02, 1, 03, 06);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Drunk Groove', '2017', '560', 01, 03, 1, 03, 06);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Hellcat Story', '2015', '110', 02, 02, 1, 03, 06);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Focus on Me - Single', '2017', '169', 02, 06, 1, 03, 07);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Black Water (Deluxe Version)', '2019', '220', 01, 05, 1, 03, 07);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Let Me Love You', '2012', '143', 02, 1, 1, 03, 07);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Let Me ', '2015', '1110', 02, 1, 1, 07, 07);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( ' Love You', '2016', '123', 02, 1, 1, 07, 07);

      INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( ' Me Love ', '2018', '110', 02, 1, 1, 07, 07);



    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Вернись', '2014', '240', 01, 05, 1, 05, 09);


    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Зеленые глаза', '2011', '420', 01, 01, 1, 05, 09);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Где ты моя половина?', '2014', '2220', 02, 02, 1, 05, 09);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Город ЗОЛОТОЙ', '2019', '110', 01, 03, 1, 05, 09);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Пьеро и Мальвина', '1999', '830', 01, 05, 1, 05, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Как ты там', '2009', '730', 01, 05, 1, 05, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Привет Андрей', '2018', '630', 01, 05, 1, 05, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ('Вечер', '2006', '430', 01, 05, 1, 07, 01);

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Буратино', '1222', '330', 01, 05, 1, 05, 01);
    

    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Солнце', '1222', '330', 01, 05, 1, 05, 01);


    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Печаль', '1222', '330', 01, 05, 1, 05, 02);


    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Боль', '1222', '330', 01, 05, 1, 05, 01);


    INSERT INTO    `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
    VALUES ( 'Рояль', '1222', '330', 01, 05, 1, 05, 01);




INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`) 
VALUES ( 'Some Nights', '192', '960', 01, 04, 1, 01, 02);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Siren Song', '2014', '1520', 01, 04, 1, 02, 09);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Любовь в Метро ', '2015', '220', 02, 06, 2, 04, 01);


INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Фарш', '2014', '460', 01, 01, 1, 06, 01);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Вечерний Ленинград', '2012', '890', 02, 02, 1, 06, 01);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ('Рыба', '2012', '110', 02, 03, 1, 06, 01);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Вечный огонь', '2011', '20', 01, 04, 1, 06, 01);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Аврора', '2007', '1310', 01, 05, 1, 06, 01);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Бабье лето', '2006', '540', 02, 06, 1, 06, 01);



INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Friendships', '2017', '520', 01, 01, 2, 02, 02);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Fall For You', '2018', '260', 02, 02, 2, 02, 02);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ('Believe In Me', '2018', '4240', 01, 03, 2, 02, 03);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Fall for You - Single', '2006', '540', 01, 04, 2, 02, 02);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Coming Back Around - Single', '2018', '340', 01, 05, 2, 02, 04);



INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Мира мало', '2017', '520', 01, 01, 2, 04, 07);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'INSTADRAMA', '2014', '520', 01, 02, 3, 04, 07);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Парень', '2015', '520', 01, 04, 3, 04, 04);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'случайная', '2018', '520', 02, 06, 3, 04, 04);



INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'To Be Mine', '2019', '520', 01, 01, 1, 03, 06);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Focus On Me', '2018', '320', 01, 02, 1, 03, 06);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Drunk Groove', '2017', '560', 01, 03, 1, 03, 06);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Hellcat Story', '2015', '110', 02, 02, 1, 03, 06);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Focus on Me - Single', '2017', '169', 02, 06, 1, 03, 07);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Black Water (Deluxe Version)', '2019', '220', 01, 05, 1, 03, 07);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Let Me Love You', '2012', '1110', 02, 01, 1, 03, 07);



INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Вернись', '2014', '240', 01, 05, 1, 05, 09);


INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ('Зеленые глаза', '2011', '420', 01, 01, 1, 05, 09);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Где ты моя половина?', '2014', '2220', 02, 02, 1, 05, 09);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Город ЗОЛОТОЙ', '2019', '110', 01, 03, 1, 05, 09);

INSERT INTO  `Music_Films` (   `Name_diska`, `Year`, `Price`, `Cod_vida_diska`, `Cod_formata`, `Cod_producer`, `Cod_singer`, `Cod_country`)
VALUES ( 'Пьеро и Мальвина', '1999', '330', 01, 05, 1, 05, 01);
-- COMMIT;